---
apiVersion: v1
kind: Namespace
metadata:
  name: 2team
---
apiVersion: v1
kind: Pod
metadata:
  name: test-apache
  namespace: 2team
spec:
  containers:
  - name: apache
    image: httpd
    ports:
    - containerPort: 80
