---
apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80		
