---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-word
  labels:
    dep: word
spec:
  selector:
    matchLabels:
      app: dep-word
  replicas: 3
  template:
    metadata:
      name: tem-word
      labels:
        app: dep-word
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.6
        imagePullPolicy: IfNotPresent
        env:
        - name: WORDPRESS_DB_HOST
          value: 10.42.0.2
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: It12345!
        ports:
        - containerPort: 80
