---
apiVersion: v1
kind: Service
metadata:
  name: svc-word
  labels:
    run: wordpress
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 32080
    protocol: TCP
  selector:
    app: dep-word
